@startuml
start
:desireFate;
if(permanence) then (limboDAO.burnAsset())
    partition #thistle "transaction"{
        if(asset type) then (eye)
            :fateCreated += amount * 10;
        else (LP)
            :fateCreated += eye balance of LP * 20;
        endif
    }
else (limboDAO.setEYEBasedAssetStake())
    partition #CornflowerBlue "transaction"{
        if(asset type) then (eye)
            :fate per day += sqrt(amount);
        else (LP)
            :fate per day += sqrt(eye balance of LP) * 2;
        endif
    }
endif
stop
@enduml

