/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type { AngbandLite, AngbandLiteInterface } from "../AngbandLite";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "powerInvoker",
        type: "address",
      },
    ],
    name: "executePower",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b5061016c806100206000396000f3fe608060405234801561001057600080fd5b506004361061002b5760003560e01c8063ede0b3b514610030575b600080fd5b61004a600480360381019061004591906100c4565b61004c565b005b8073ffffffffffffffffffffffffffffffffffffffff1663cab7f5216040518163ffffffff1660e01b8152600401600060405180830381600087803b15801561009457600080fd5b505af11580156100a8573d6000803e3d6000fd5b5050505050565b6000813590506100be8161011f565b92915050565b6000602082840312156100d657600080fd5b60006100e4848285016100af565b91505092915050565b60006100f8826100ff565b9050919050565b600073ffffffffffffffffffffffffffffffffffffffff82169050919050565b610128816100ed565b811461013357600080fd5b5056fea264697066735822122095a5485318c77f0ae5003c8d5c949642e823dac312592bc36c9a81f8333abddc64736f6c63430008040033";

export class AngbandLite__factory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<AngbandLite> {
    return super.deploy(overrides || {}) as Promise<AngbandLite>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): AngbandLite {
    return super.attach(address) as AngbandLite;
  }
  connect(signer: Signer): AngbandLite__factory {
    return super.connect(signer) as AngbandLite__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): AngbandLiteInterface {
    return new utils.Interface(_abi) as AngbandLiteInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): AngbandLite {
    return new Contract(address, _abi, signerOrProvider) as AngbandLite;
  }
}
