/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { AngbandLike, AngbandLikeInterface } from "../AngbandLike";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "powerInvoker",
        type: "address",
      },
    ],
    name: "executePower",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class AngbandLike__factory {
  static readonly abi = _abi;
  static createInterface(): AngbandLikeInterface {
    return new utils.Interface(_abi) as AngbandLikeInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): AngbandLike {
    return new Contract(address, _abi, signerOrProvider) as AngbandLike;
  }
}
