/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  BehodlerLiteLike,
  BehodlerLiteLikeInterface,
} from "../BehodlerLiteLike";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "inputToken",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "addLiquidity",
    outputs: [
      {
        internalType: "uint256",
        name: "deltaSCX",
        type: "uint256",
      },
    ],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "token",
        type: "address",
      },
      {
        internalType: "bool",
        name: "burnable",
        type: "bool",
      },
    ],
    name: "setTokenBurnable",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class BehodlerLiteLike__factory {
  static readonly abi = _abi;
  static createInterface(): BehodlerLiteLikeInterface {
    return new utils.Interface(_abi) as BehodlerLiteLikeInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): BehodlerLiteLike {
    return new Contract(address, _abi, signerOrProvider) as BehodlerLiteLike;
  }
}
