/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  FlashGovernanceArbiterLike,
  FlashGovernanceArbiterLikeInterface,
} from "../FlashGovernanceArbiterLike";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "sender",
        type: "address",
      },
      {
        internalType: "address",
        name: "target",
        type: "address",
      },
      {
        internalType: "bool",
        name: "emergency",
        type: "bool",
      },
    ],
    name: "assertGovernanceApproved",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "targetContract",
        type: "address",
      },
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
      {
        internalType: "address",
        name: "asset",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "burnFlashGovernanceAsset",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "v1",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "v2",
        type: "uint256",
      },
    ],
    name: "enforceTolerance",
    outputs: [],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "int256",
        name: "v1",
        type: "int256",
      },
      {
        internalType: "int256",
        name: "v2",
        type: "int256",
      },
    ],
    name: "enforceToleranceInt",
    outputs: [],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bool",
        name: "enforce",
        type: "bool",
      },
    ],
    name: "setEnforcement",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class FlashGovernanceArbiterLike__factory {
  static readonly abi = _abi;
  static createInterface(): FlashGovernanceArbiterLikeInterface {
    return new utils.Interface(_abi) as FlashGovernanceArbiterLikeInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): FlashGovernanceArbiterLike {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as FlashGovernanceArbiterLike;
  }
}
