/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { LachesisLike, LachesisLikeInterface } from "../LachesisLike";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "token",
        type: "address",
      },
    ],
    name: "cut",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "token",
        type: "address",
      },
      {
        internalType: "bool",
        name: "valid",
        type: "bool",
      },
      {
        internalType: "bool",
        name: "burnable",
        type: "bool",
      },
    ],
    name: "measure",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class LachesisLike__factory {
  static readonly abi = _abi;
  static createInterface(): LachesisLikeInterface {
    return new utils.Interface(_abi) as LachesisLikeInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): LachesisLike {
    return new Contract(address, _abi, signerOrProvider) as LachesisLike;
  }
}
