/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  LimboAddTokenToBehodlerPowerLike,
  LimboAddTokenToBehodlerPowerLikeInterface,
} from "../LimboAddTokenToBehodlerPowerLike";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "soul",
        type: "address",
      },
      {
        internalType: "bool",
        name: "burnable",
        type: "bool",
      },
    ],
    name: "parameterize",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class LimboAddTokenToBehodlerPowerLike__factory {
  static readonly abi = _abi;
  static createInterface(): LimboAddTokenToBehodlerPowerLikeInterface {
    return new utils.Interface(
      _abi
    ) as LimboAddTokenToBehodlerPowerLikeInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): LimboAddTokenToBehodlerPowerLike {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as LimboAddTokenToBehodlerPowerLike;
  }
}
