/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  LiquidiyReceiverLike,
  LiquidiyReceiverLikeInterface,
} from "../LiquidiyReceiverLike";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "baseToken",
        type: "address",
      },
    ],
    name: "drain",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class LiquidiyReceiverLike__factory {
  static readonly abi = _abi;
  static createInterface(): LiquidiyReceiverLikeInterface {
    return new utils.Interface(_abi) as LiquidiyReceiverLikeInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): LiquidiyReceiverLike {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as LiquidiyReceiverLike;
  }
}
