/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { MigratorLike, MigratorLikeInterface } from "../MigratorLike";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "token",
        type: "address",
      },
      {
        internalType: "bool",
        name: "burnable",
        type: "bool",
      },
      {
        internalType: "uint256",
        name: "flanQuoteDivergenceTolerance",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "minQuoteWaitDuration",
        type: "uint256",
      },
    ],
    name: "execute",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class MigratorLike__factory {
  static readonly abi = _abi;
  static createInterface(): MigratorLikeInterface {
    return new utils.Interface(_abi) as MigratorLikeInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): MigratorLike {
    return new Contract(address, _abi, signerOrProvider) as MigratorLike;
  }
}
