/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  MorgothTokenApproverLike,
  MorgothTokenApproverLikeInterface,
} from "../MorgothTokenApproverLike";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "token",
        type: "address",
      },
    ],
    name: "approved",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class MorgothTokenApproverLike__factory {
  static readonly abi = _abi;
  static createInterface(): MorgothTokenApproverLikeInterface {
    return new utils.Interface(_abi) as MorgothTokenApproverLikeInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): MorgothTokenApproverLike {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as MorgothTokenApproverLike;
  }
}
