/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  ProposalFactoryLike,
  ProposalFactoryLikeInterface,
} from "../ProposalFactoryLike";

const _abi = [
  {
    inputs: [],
    name: "soulUpdateProposal",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "proposal",
        type: "address",
      },
    ],
    name: "toggleWhitelistProposal",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class ProposalFactoryLike__factory {
  static readonly abi = _abi;
  static createInterface(): ProposalFactoryLikeInterface {
    return new utils.Interface(_abi) as ProposalFactoryLikeInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ProposalFactoryLike {
    return new Contract(address, _abi, signerOrProvider) as ProposalFactoryLike;
  }
}
