/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { SnufferCap, SnufferCapInterface } from "../SnufferCap";

const _abi = [
  {
    inputs: [],
    name: "_liquidityReceiver",
    outputs: [
      {
        internalType: "contract LiquidityReceiverLike",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "pyroToken",
        type: "address",
      },
      {
        internalType: "address",
        name: "targetContract",
        type: "address",
      },
      {
        internalType: "enum FeeExemption",
        name: "exempt",
        type: "uint8",
      },
    ],
    name: "snuff",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class SnufferCap__factory {
  static readonly abi = _abi;
  static createInterface(): SnufferCapInterface {
    return new utils.Interface(_abi) as SnufferCapInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): SnufferCap {
    return new Contract(address, _abi, signerOrProvider) as SnufferCap;
  }
}
