@startuml
start
if(limbo enabled) then (yes)
    partition #MistyRose "update soul"{
        if(soul is initialized) then (yes)
            if(total staked balance of soul>0) then(yes)
                :mint flan => duration*flanPerSecond*relativeAllocPoints;
            endif
            :update reward update timestamp for soul;
        else (no)
            #lightpink:revert;
            stop
        endif
    }
    if(exitPenalty > 0) then (yes)
        #lightpink:revert;
        stop
    else (penalty == 0)
        if(pending reward >0) then (yes)
            :transfer flan to msg.sender;
            :incremement reward debt by pending;
        endif
    endif
else (no)
    #pink:revert;
    stop
endif
stop
@enduml