@startuml
start
#PaleTurquoise:Limbo.stake(address token, uint256 amount);
partition #LightGrey "transaction"{
    if(limbo is enabled) then(yes)
        partition #MistyRose "update soul"{
            if(soul is initialized) then (yes)
                if(total staked balance of soul>0) then(yes)
                    :mint flan => duration*flanPerSecond*relativeAllocPoints;
                endif
                :update reward update timestamp for soul;
            else (no)
                #lightpink:revert;
                stop
            endif
        }
        if(soul is in staking state) then (yes)
            'main sequence
            :transfer amount from user to limbo;
            if(user has accumulated rewards previously on this token) then (yes)
                :transfer accumulated rewards to user;
            else(no)

            endif
            if (new balance of token on limbo > migration threshold) then (yes)
                :set soul state to 'waitingToCross';
                :set stakingEndTimeStamp to now;
            else (no)
            endif

        else (no)
            #lightpink:revert;
            stop
        endif
    else (no)
        #lightpink:revert;
        stop
    endif
}
stop
@enduml