/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface AMMHelperInterface extends ethers.utils.Interface {
  functions: {
    "buyFlanAndBurn(address,uint256,address)": FunctionFragment;
    "generateFLNQuote()": FunctionFragment;
    "minAPY_to_FPS(uint256,uint256)": FunctionFragment;
    "stabilizeFlan(uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "buyFlanAndBurn",
    values: [string, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "generateFLNQuote",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "minAPY_to_FPS",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "stabilizeFlan",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "buyFlanAndBurn",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "generateFLNQuote",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "minAPY_to_FPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "stabilizeFlan",
    data: BytesLike
  ): Result;

  events: {};
}

export class AMMHelper extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: AMMHelperInterface;

  functions: {
    buyFlanAndBurn(
      inputToken: string,
      amount: BigNumberish,
      recipient: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    generateFLNQuote(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    minAPY_to_FPS(
      minAPY: BigNumberish,
      daiThreshold: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { fps: BigNumber }>;

    stabilizeFlan(
      rectangleOfFairness: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  buyFlanAndBurn(
    inputToken: string,
    amount: BigNumberish,
    recipient: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  generateFLNQuote(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  minAPY_to_FPS(
    minAPY: BigNumberish,
    daiThreshold: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  stabilizeFlan(
    rectangleOfFairness: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    buyFlanAndBurn(
      inputToken: string,
      amount: BigNumberish,
      recipient: string,
      overrides?: CallOverrides
    ): Promise<void>;

    generateFLNQuote(overrides?: CallOverrides): Promise<void>;

    minAPY_to_FPS(
      minAPY: BigNumberish,
      daiThreshold: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    stabilizeFlan(
      rectangleOfFairness: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    buyFlanAndBurn(
      inputToken: string,
      amount: BigNumberish,
      recipient: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    generateFLNQuote(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    minAPY_to_FPS(
      minAPY: BigNumberish,
      daiThreshold: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    stabilizeFlan(
      rectangleOfFairness: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    buyFlanAndBurn(
      inputToken: string,
      amount: BigNumberish,
      recipient: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    generateFLNQuote(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    minAPY_to_FPS(
      minAPY: BigNumberish,
      daiThreshold: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    stabilizeFlan(
      rectangleOfFairness: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
