/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface FlashGovernanceArbiterLikeInterface extends ethers.utils.Interface {
  functions: {
    "assertGovernanceApproved(address,address,bool)": FunctionFragment;
    "burnFlashGovernanceAsset(address,address,address,uint256)": FunctionFragment;
    "enforceTolerance(uint256,uint256)": FunctionFragment;
    "enforceToleranceInt(int256,int256)": FunctionFragment;
    "setEnforcement(bool)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "assertGovernanceApproved",
    values: [string, string, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "burnFlashGovernanceAsset",
    values: [string, string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "enforceTolerance",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "enforceToleranceInt",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setEnforcement",
    values: [boolean]
  ): string;

  decodeFunctionResult(
    functionFragment: "assertGovernanceApproved",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "burnFlashGovernanceAsset",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "enforceTolerance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "enforceToleranceInt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setEnforcement",
    data: BytesLike
  ): Result;

  events: {};
}

export class FlashGovernanceArbiterLike extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: FlashGovernanceArbiterLikeInterface;

  functions: {
    assertGovernanceApproved(
      sender: string,
      target: string,
      emergency: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    burnFlashGovernanceAsset(
      targetContract: string,
      user: string,
      asset: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    enforceTolerance(
      v1: BigNumberish,
      v2: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[void]>;

    enforceToleranceInt(
      v1: BigNumberish,
      v2: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[void]>;

    setEnforcement(
      enforce: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  assertGovernanceApproved(
    sender: string,
    target: string,
    emergency: boolean,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  burnFlashGovernanceAsset(
    targetContract: string,
    user: string,
    asset: string,
    amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  enforceTolerance(
    v1: BigNumberish,
    v2: BigNumberish,
    overrides?: CallOverrides
  ): Promise<void>;

  enforceToleranceInt(
    v1: BigNumberish,
    v2: BigNumberish,
    overrides?: CallOverrides
  ): Promise<void>;

  setEnforcement(
    enforce: boolean,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    assertGovernanceApproved(
      sender: string,
      target: string,
      emergency: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    burnFlashGovernanceAsset(
      targetContract: string,
      user: string,
      asset: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    enforceTolerance(
      v1: BigNumberish,
      v2: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    enforceToleranceInt(
      v1: BigNumberish,
      v2: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setEnforcement(enforce: boolean, overrides?: CallOverrides): Promise<void>;
  };

  filters: {};

  estimateGas: {
    assertGovernanceApproved(
      sender: string,
      target: string,
      emergency: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    burnFlashGovernanceAsset(
      targetContract: string,
      user: string,
      asset: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    enforceTolerance(
      v1: BigNumberish,
      v2: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    enforceToleranceInt(
      v1: BigNumberish,
      v2: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    setEnforcement(
      enforce: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    assertGovernanceApproved(
      sender: string,
      target: string,
      emergency: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    burnFlashGovernanceAsset(
      targetContract: string,
      user: string,
      asset: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    enforceTolerance(
      v1: BigNumberish,
      v2: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    enforceToleranceInt(
      v1: BigNumberish,
      v2: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    setEnforcement(
      enforce: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
