/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface LimboAddTokenToBehodlerTestNetInterface
  extends ethers.utils.Interface {
  functions: {
    "invoke(bytes32,address)": FunctionFragment;
    "parameterize(address,bool)": FunctionFragment;
    "params()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "invoke",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "parameterize",
    values: [string, boolean]
  ): string;
  encodeFunctionData(functionFragment: "params", values?: undefined): string;

  decodeFunctionResult(functionFragment: "invoke", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "parameterize",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "params", data: BytesLike): Result;

  events: {
    "PowerInvoked(address,bytes32,bytes32)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "PowerInvoked"): EventFragment;
}

export class LimboAddTokenToBehodlerTestNet extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: LimboAddTokenToBehodlerTestNetInterface;

  functions: {
    invoke(
      minion: BytesLike,
      sender: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    parameterize(
      soul: string,
      burnable: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    params(
      overrides?: CallOverrides
    ): Promise<
      [string, boolean, string] & {
        soul: string;
        burnable: boolean;
        limbo: string;
      }
    >;
  };

  invoke(
    minion: BytesLike,
    sender: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  parameterize(
    soul: string,
    burnable: boolean,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  params(
    overrides?: CallOverrides
  ): Promise<
    [string, boolean, string] & {
      soul: string;
      burnable: boolean;
      limbo: string;
    }
  >;

  callStatic: {
    invoke(
      minion: BytesLike,
      sender: string,
      overrides?: CallOverrides
    ): Promise<void>;

    parameterize(
      soul: string,
      burnable: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    params(
      overrides?: CallOverrides
    ): Promise<
      [string, boolean, string] & {
        soul: string;
        burnable: boolean;
        limbo: string;
      }
    >;
  };

  filters: {
    PowerInvoked(
      user?: null,
      minion?: null,
      domain?: null
    ): TypedEventFilter<
      [string, string, string],
      { user: string; minion: string; domain: string }
    >;
  };

  estimateGas: {
    invoke(
      minion: BytesLike,
      sender: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    parameterize(
      soul: string,
      burnable: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    params(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    invoke(
      minion: BytesLike,
      sender: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    parameterize(
      soul: string,
      burnable: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    params(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
