/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface SoulReaderInterface extends ethers.utils.Interface {
  functions: {
    "CrossingParameters(address,address)": FunctionFragment;
    "ExpectedCrossingBonus(address,address,address)": FunctionFragment;
    "ExpectedCrossingBonusRate(address,address,address)": FunctionFragment;
    "GetPendingReward(address,address,address)": FunctionFragment;
    "SoulStats(address,address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "CrossingParameters",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "ExpectedCrossingBonus",
    values: [string, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "ExpectedCrossingBonusRate",
    values: [string, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "GetPendingReward",
    values: [string, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "SoulStats",
    values: [string, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "CrossingParameters",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ExpectedCrossingBonus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ExpectedCrossingBonusRate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "GetPendingReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "SoulStats", data: BytesLike): Result;

  events: {};
}

export class SoulReader extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: SoulReaderInterface;

  functions: {
    CrossingParameters(
      token: string,
      _limbo: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber, BigNumber]>;

    ExpectedCrossingBonus(
      holder: string,
      token: string,
      _limbo: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { flanBonus: BigNumber }>;

    ExpectedCrossingBonusRate(
      holder: string,
      token: string,
      _limbo: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { bonusRate: BigNumber }>;

    GetPendingReward(
      account: string,
      token: string,
      _limbo: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    SoulStats(
      token: string,
      _limbo: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber, BigNumber]>;
  };

  CrossingParameters(
    token: string,
    _limbo: string,
    overrides?: CallOverrides
  ): Promise<[BigNumber, BigNumber, BigNumber]>;

  ExpectedCrossingBonus(
    holder: string,
    token: string,
    _limbo: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  ExpectedCrossingBonusRate(
    holder: string,
    token: string,
    _limbo: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  GetPendingReward(
    account: string,
    token: string,
    _limbo: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  SoulStats(
    token: string,
    _limbo: string,
    overrides?: CallOverrides
  ): Promise<[BigNumber, BigNumber, BigNumber]>;

  callStatic: {
    CrossingParameters(
      token: string,
      _limbo: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber, BigNumber]>;

    ExpectedCrossingBonus(
      holder: string,
      token: string,
      _limbo: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    ExpectedCrossingBonusRate(
      holder: string,
      token: string,
      _limbo: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    GetPendingReward(
      account: string,
      token: string,
      _limbo: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    SoulStats(
      token: string,
      _limbo: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber, BigNumber]>;
  };

  filters: {};

  estimateGas: {
    CrossingParameters(
      token: string,
      _limbo: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    ExpectedCrossingBonus(
      holder: string,
      token: string,
      _limbo: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    ExpectedCrossingBonusRate(
      holder: string,
      token: string,
      _limbo: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    GetPendingReward(
      account: string,
      token: string,
      _limbo: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    SoulStats(
      token: string,
      _limbo: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    CrossingParameters(
      token: string,
      _limbo: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    ExpectedCrossingBonus(
      holder: string,
      token: string,
      _limbo: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    ExpectedCrossingBonusRate(
      holder: string,
      token: string,
      _limbo: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    GetPendingReward(
      account: string,
      token: string,
      _limbo: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    SoulStats(
      token: string,
      _limbo: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
